### ISSUE TITLE
[Bug]:  Costs not showing

### ISSUE THREAD

**Issue by DanCargill** [PredictMobile/tickets#16]
### Product

Sensabill

### Describe the bug?

The costs for customer ref 187578506 is not showing for October 2023

### What did you expect to happen?

Costs to show in line with other months

### Checked for existing ticket

- [X] I confirm I have checked to see that my issue has not already been reported.
- [X] I confirm I have not included any sensitive information.

**Comment by warrickhill** [comment]
Hi Dan.

We have investigated the issue, and it seems the file have attempted to download the max number of times.

We have reset the count and attempted to download again. The first time EE website reported the down was not yet ready, however on the 2nd attempt it did successfully download. The cliects date is now up to date
