### ISSUE TITLE
[Bug]: Incorrect costs

### ISSUE THREAD

**Issue by DanCargill** [PredictMobile/tickets#17]
### Product

None

### Describe the bug?

The recurring costs have pulled through incorrectly on customer ref 98772581, unsure if this has also impacted other costs.

### What did you expect to happen?

Costs pull through correctly as per previously recurring costs.

### Checked for existing ticket

- [X] I confirm I have checked to see that my issue has not already been reported.
- [X] I confirm I have not included any sensitive information.

**Comment by scottdykes1611** [comment]
Hi Dan.

The missing Nov and Dec recurring costs have now pulled through into Sensabill.

The Dec file had been successfully prepared and likely would have come through automatically, however the Nov file had reached the max number of attempts and needed to be manually run again. (This was the same issue as in your previous ticket)

We've found a few files with the same issue in other customers so these are running now.
