### ISSUE TITLE
[Bug]: UK Data not showing

### ISSUE THREAD

**Issue by DanCargill** [PredictMobile/tickets#19]
### Product

None

### Describe the bug?

UK Data isn't showing for customer ref 194046406 in July and August.

### What did you expect to happen?

n/a

### Checked for existing ticket

- [X] I confirm I have checked to see that my issue has not already been reported.
- [X] I confirm I have not included any sensitive information.

**Comment by scottdykes1611** [comment]
Hi Dan,

We have re-run the analysis on the files for those months and the UK data seems to be showing properly now
