### ISSUE TITLE
Tariff Names

### ISSUE THREAD

**Issue by lukelaneres1** [PredictMobile/tickets#23]
### Product

None

### Is your feature request related to a problem? Please describe.

N/A

### Describe the solution you'd like.

Is it possible to have tariff names displayed somewhere for each line? For example, when you clock in to total cost from the dashboard, it would be useful to have a column next to the "Number" and "User" column that pulled the tariff name off of the invoices (for example Business Connect Sharer" or "12 GB Business Essential SIMO" etc

### Checked for existing ticket

- [X] I confirm I have checked to see that this feature has not already been requested.
- [X] I confirm I have not included any sensitive information.

**Comment by warrickhill** [comment]
Hi. We have looked into this, and unfortunately this is not possible as most invoices and reports we pull from the networks do not have this info.

We are working an alternative method of achieving functionally similar to what you have described and will update this ticket when it is ready
