### ISSUE TITLE
[Feature]: Send reminder emails for selecting a supplier to customer

### ISSUE THREAD

**Issue by scottdykes1611** [PredictMobile/tickets#24]
### Product

Predict

### Is your feature request related to a problem? Please describe.

Customers need to be pushed to select a supplier

### Describe the solution you'd like.

Once responses are ready for a customer to look at, every 2 days send a reminder email until the customer chooses a supplier

### Checked for existing ticket

- [X] I confirm I have checked to see that this feature has not already been requested.
- [X] I confirm I have not included any sensitive information.

**Comment by FinlayKilcullen** [comment]
CHANGES:
Emails should be sent in following intervals
the first email can extend deadline
5,2,3,1 days
T-4, T-1 hour and T-0 hours sorry you’ve missed offers

**Comment by scottdykes1611** [comment]
This is ready and merged. The emails are not yet being sent though pending a response with consistent terms from lawyer.
