### ISSUE TITLE
[Feature]: Date loaded column

### ISSUE THREAD

**Issue by lukelaneres1** [PredictMobile/tickets#28]
### Product

None

### Is your feature request related to a problem? Please describe.

It's not a fault as such but it is a pain point we have experienced. On the odd occasion that an account's invoice fails to load due to an issue it may take a number of days before it appears on the dashboard with the latest invoice info loaded. By this time, many other accounts who have invoice dates later in the month may have loaded and this buries the freshly loaded account invoice further down the dashboard where it is not as easy to spot.

### Describe the solution you'd like.

A column on the dashboard which date stamps the moment that an invoice was fully loaded to Sensabill. This would allow us to filter the dashbaord by latest upload to Sensabill date rather than just by latest invoice date making it less likely that we miss out on reviewing an invoice!

### Checked for existing ticket

- [X] I confirm I have checked to see that this feature has not already been requested.
- [X] I confirm I have not included any sensitive information.

**Comment by scottdykes1611** [comment]
The "Latest Upload Date" column has been added to the table of customers.
By default the table is now sorted by the most recent upload date
