### ISSUE TITLE
[Bug]: Invoice costs don't match up with Sensabill Table

### ISSUE THREAD

**Issue by scottdykes1611** [PredictMobile/tickets#36]
### Product

None

### Describe the bug?

The costs shown in the voice don't match the total costs for all users for that month (clientId: 16130a9b-4558-4d1b-9dcf-1c3071a22d24) (month: March)

### What did you expect to happen?

The costs should match

### Checked for existing ticket

- [X] I confirm I have checked to see that my issue has not already been reported.
- [X] I confirm I have not included any sensitive information.

**Comment by DanCargill** [comment]
Hi,

Is there an update please?

Thanks,

**Comment by scottdykes1611** [comment]
Hi Dan,

I've sent an email to address this issue, and closing the ticket now. Feel free to re-open it if you feel more needs to be done to address this.
